---
title: "Linear Regression"
date: "`03-13-2023`"
output:
  html_document:
    theme: default
    highlight: textmate
    toc: yes
    toc_float: yes
    fig_width: 9.67
    fig_height: 6
    fig_caption: yes
  pdf_document:
    toc: yes
---


# Important Note
To clear the workspace, use the command below:
```{r}
rm(list = ls())
```

# Data

```{r}
N <- 10000 # nolint
error_sd <- 10
x_data <- 1:N # non-random variable (explanatory variable)
error_data <- rnorm(N, mean = 0, sd = error_sd) # random variable and constant variance #nolint
b_0 <- 1 # intercept
b_1 <- 10 # slope
y_data <- b_0 + b_1 * x_data + error_data # response variable (Random variable)

x_data <-c(.02,.07,.11,.15)
y_data<-c(242,237,231,201)
N <- length(x_data)
y_bar <- mean(y_data)
x_bar <- mean(x_data)

data <- data.frame(cbind(x_data, y_data))
```

# Linear Regression
```{r}
# ydata ~ xdata means (ydata = b_0 + b_1 * xdata)
lm_model <- lm(y_data ~ x_data, data = data)
summary(lm_model)

b_1_estimator <- coef(lm_model)[2]
b_0_estimator <- coef(lm_model)[1]

y_data_hat <- b_0_estimator + b_1_estimator * x_data
y_data_hat
```

## Hand Calculations

```{r}
pearson_corr <- cor(x_data, y_data, method = "pearson")
spearman_corr <- cor(x_data, y_data, method = "spearman")
b_1_estimator <- pearson_corr * sd(y_data) / sd(x_data)
b_0_estimator <- y_bar - x_bar * b_1_estimator

print(b_0_estimator)
print(b_1_estimator)
print(pearson_corr)
print(pearson_corr ^ 2)
print(spearman_corr)

SSxx <- sum((x_data - x_bar)^2)
SSyy <- sum((y_data - y_bar)^2)
SSxy <- sum((y_data - y_bar) * (x_data - x_bar))

SSR <- sum((y_data_hat - y_bar)^2)
SSE <- sum((y_data - y_data_hat)^2)
SST <- sum((y_data - y_bar)^2)

print(SSR)
print(SSE)
print(SSR + SSE)
print(SST)

dof_r <- 1
dof_e <- N - 2
MSR <- SSR / dof_r
MSE <- SSE / dof_e
```

# Plots

## X-Y Scatter plot
```{r}
plot(x_data, y_data)
```

## X-Error Scatter plot
```{r}
plot(x_data, error_data)
```

## Errors histogram

```{r}
hist(error_data) # must be a bell shape centered around 0
```

## errors QQ - plot
```{r}
# straight line if our errors are normally distributed with constant variance
qqnorm(error_data)
qqline(error_data)
```

## ANOVA table for Linear Regression
```{r}
aov <- aov(y_data ~ x_data, data = data)
summary(aov)

# Regression Sum of Squares: SSR = sigma (Y_hat_i - Y_bar)^2
# Error Sum of Squares     : SSE = sigma (Y_hat_i - Y_i)^2
# Total Sum of Squares     : SST = sigma (Y_i - Y_bar)^2
```

# Confidence Interval
```{r}
alpha <- 0.05

# In-built function
x_star <- c(0.1, 0.2)
x_star_data <- data.frame(x_data = x_star)
predict(lm_model, x_star_data,
        se.fit = TRUE, interval = "confidence", level = 1 - alpha)

# Long Hand calculations
mu_hat_x_star <- b_0_estimator + b_1_estimator * x_star

print(mu_hat_x_star)

sd_mu_hat_x_star <- sqrt(MSE * ((1 / N) + ((x_bar - x_star)^2 / SSxx)))
print(sd_mu_hat_x_star)

ci_lo <- mu_hat_x_star - qt(alpha / 2, N - 2, lower.tail = FALSE) * sd_mu_hat_x_star
ci_hi <- mu_hat_x_star + qt(alpha / 2, N - 2, lower.tail = FALSE) * sd_mu_hat_x_star

ci_frame <- data.frame(x_star = x_star, ci_lo = ci_lo, ci_hi = ci_hi)

print(ci_frame)
```
# Prediction Interval
```{r}
alpha <- 0.05

# In-built function
x_star <- c(0.1, 0.2)
x_star_data <- data.frame(x_data = x_star)
predict(lm_model, x_star_data,
        se.fit = TRUE, interval = "prediction", level = 1 - alpha)

# Long Hand calculations
mu_hat_x_star <- b_0_estimator + b_1_estimator * x_star

print(mu_hat_x_star)

sd_mu_hat_x_star <- sqrt(MSE * (1 + (1 / N) + ((x_bar - x_star)^2 / SSxx)))
print(sd_mu_hat_x_star)

ci_lo <- mu_hat_x_star -
            qt(alpha / 2, N - 2, lower.tail = FALSE) * sd_mu_hat_x_star
ci_hi <- mu_hat_x_star +
            qt(alpha / 2, N - 2, lower.tail = FALSE) * sd_mu_hat_x_star

ci_frame <- data.frame(x_star = x_star, ci_lo = ci_lo, ci_hi = ci_hi)

print(ci_frame)
```