---
title: "Matrices"
date: "`09-27-2024`"
output:
  html_document:
    theme: default
    highlight: textmate
    toc: yes
    toc_float: yes
    fig_width: 9.67
    fig_height: 6
    fig_caption: yes
  pdf_document:
    toc: yes
---

# Important Note

To clear the workspace, use the command below:

```{r}
rm(list = ls())
```

# Matrix

To define a matrix:

```{r}
m <- matrix(c(1,2,3,4,5,6), nrow=3, byrow=FALSE)
print(m)

# or

m <- matrix(c(1,2,3,4,5,6), ncol=3, byrow = TRUE)
print(m)
```

# Matrix Operations

## Data

```{r}
m_data <- c(1,2,3,4,5,6, 7, 8, 1)
p = 3
q = 3

n_data <- c(1,2,3,4,5,6, 7, 8, 1)
r = 3
s = 3

m <- matrix(m_data, nrow=p, byrow=TRUE)
n <- matrix(m_data, nrow=r, byrow=TRUE)

print(m)
print(n)
```
## Transpose
```{r}
mT <- t(m)
nT <- t(n)

print(mT)
print(nT)
```


## Multiply
```{r}
ans <- m %*% n

print(ans)
```


## Inverse
```{r}
# NOTE: Must be a square matrix to calculate inverse

# use in-built solve()
inv1 <- solve(m)
inv2 <- solve(n)

print(inv1)
print(inv2)
```

# Playground
```{r}
library(MASS)
x_data <- c(1,1,1,1,1,-2,1,1,1,1,-1,1,1,-1,-2,1,-1,1)
nrow <- 6
ncol <- 3

x <- matrix(x_data, nrow=nrow, ncol=ncol,byrow=TRUE)
xT <- t(x)
y <- matrix(c(3,2,1,1,2,0), ncol=1)


print(x)
print(xT)
print(y)



print(fractions(solve(xT %*% x) %*% xT %*% y))


lm(y~x[,2] + x[,3])

```


```{r}
A <- matrix(c(1,0,3,0,0,2,3,2,4), byrow=TRUE, nrow=3)
Y <- c(3,0,1)
b <- c(-3,0,1)

A %*% Y + b

cov(A %*% Y + b)

A %*% Y %*% t(A)
```


















